import { LanguageCode } from './constants/languages';
type BatteryType = 'AA' | 'AAA' | 'C' | 'D' | '9V' | 'Button Cell' | 'other/none';
type toyFeature = 'Light-Up' | 'Sound' | 'Motion'| 'Vibration' | 'Remote-Controlled';
// Should screwdriver type be type classification? Or just a string?


export interface ToyMetadata {
  id?: string; // Optional because it will be generated by the database
  name: Record<LanguageCode, string>; // e.g., { en: "Toy Car", es: "Coche de Juguete" }
  brand: string;
  upc: string;
  purchase_link: string; 
  screw_type: string;
  battery_type: BatteryType;
  battery_count: number;
  toy_feature: toyFeature[];
  contributor: string; 
}

export interface instructionStep{
  picture: PictureMetadata;
  step_number: number;
  description: Record<LanguageCode, string>; // e.g., { en: "Remove the battery cover", es: "Retire la tapa de la batería" }
}
export interface PictureMetadata {
  picture_url: string;             // URL to the picture, stored in Supabase Storage
  alt_text: Record<LanguageCode, string>;// e.g., { en: "Battery compartment of the toy", es: "Compartimento de la batería del juguete" }
  caption: Record<LanguageCode, string>; // e.g., { en: "A picture of the toy's battery compartment", es: "Una imagen del compartimento de la batería del juguete" }
  picture_id: string;              //unique identifier for the picture, a UUID
  toy_id: string;                  // Foreign key to associate with the toy (though its in the same database, it's still good to have this for clarity and potential future use)
}

/**
 * Creates a picture entry. 
 * If 'caption' is just a string, it defaults to English ('en').
 * If it's already a Record, it uses it as-is.
 */
export const createPictureEntry = (
  toyId: string, 
  alt: string | Record<string, string>, 
  caption: string | Record<string, string> = ""
): PictureMetadata => {
  
  // Logic to handle "Just English" vs "Full Record"
  const localizedAlt = typeof alt === 'string' 
    ? { en: alt } 
    : alt;
  const localizedCaption = typeof caption === 'string' 
    ? { en: caption } 
    : caption;

  return {
    picture_url: '', 
    alt_text: localizedAlt,
    caption: localizedCaption,
    picture_id: crypto.randomUUID(),
    toy_id: toyId,
  };
};